name: Increment tests

on: 
  workflow_dispatch:

env:
  INITIAL_VERSION_CODE: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Read version.properties file
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: ci-versions.properties
          property: versionCode
          default: 1000
      
      - name: Increment version code
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "VERSION_CODE=$(($NUM + $INITIAL_VERSION_CODE))" >> $GITHUB_ENV

      - name: 'Perform Operation with ID ${{ env.VERSION_CODE }}'
        run: echo "Success!"
