name: Increment tests

on: 
  workflow_dispatch:

env:
  INITIAL_VERSION_CODE: ${{ 1000 }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:      
      - name: Increment version code
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "VERSION_CODE=$(($NUM + $INITIAL_VERSION_CODE))" >> $GITHUB_ENV

      - name: 'Perform Operation with ID ${{ env.VERSION_CODE }}'
        run: echo "Success!"
